Card("Second heart", power=10, chances=2, powMod=5, desc=[
    "Nice try, too bad",
    "there's another",
    "one.",
    "",
    "> Effects apply on",
    "  clash loss too.",
    "> Remove all bleed.",
    "> Heal to half of",
    "  your max HP.",
    "> Gain 5 shock.",
    "> Exhaust card.",
], attackScripts={"onHit": "card-scripts/second_heart.atk", "onLose": "card-scripts/second_heart.atk"}, isDefensive=True, exhaust=True, rarity=1, cost=[
    "Sourceless panic rushes",
    "through your body.",
    "Something beyond your",
    "control, as a human.",
    "Panic turns into fear.",
    "Fear turns into anger.",
    "Anger, in its most pure",
    "and animalistic form.",
    "Even if this strange",
    "sensation lasted for",
    "no longer than a few",
    "seconds, it shook you",
    "to your core.",
])