Card("Enrage", power=10, chances=2, powMod=5, desc=[
    "I don't mind dying,",
    "but I want to see your",
    "corpse before I go.",
    "",
    "> Effects apply on",
    "  clash loss too.",
    "> Remove all shock.",
    "> Gain 10 block.",
    "> Gain +5 ATK.",
    "> Gain 1 bleed for every",
    "  10 HP you have until",
    "  the end of combat.",
    "> Exhaust card.",
], attackScripts={"onHit": "card-scripts/enrage.atk", "onLose": "card-scripts/enrage.atk"}, isDefensive=True, exhaust=True, rarity=1, cost=[
    "Sourceless panic rushes",
    "through your body.",
    "Something beyond your",
    "control, as a human.",
    "Panic turns into fear.",
    "Fear turns into anger.",
    "Anger, in its most pure",
    "and animalistic form.",
    "Even if this strange",
    "sensation lasted for",
    "no longer than a few",
    "seconds, it shook you",
    "to your core.",
])